//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AturinKozlovNegmatov_Praktika2022_LokoTeh.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PraktikaEntities : DbContext
    {
        public PraktikaEntities()
            : base("name=PraktikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Запчасти> Запчасти { get; set; }
        public virtual DbSet<Поезда> Поезда { get; set; }
        public virtual DbSet<Склады> Склады { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Типы> Типы { get; set; }
        public virtual DbSet<Учет_Запчастей> Учет_Запчастей { get; set; }
    }
}
