//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AturinKozlovNegmatov_Praktika2022_LokoTeh.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запчасти
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Запчасти()
        {
            this.Учет_Запчастей = new HashSet<Учет_Запчастей>();
        }
    
        public int Id_Zapchasti { get; set; }
        public string Name_Zapchast { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Sklad { get; set; }
    
        public virtual Склады Склады { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учет_Запчастей> Учет_Запчастей { get; set; }
    }
}
