//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AturinKozlovNegmatov_Praktika2022_LokoTeh.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поезда
    {
        public int Id_poezda { get; set; }
        public string Name_poezda { get; set; }
        public string Photo { get; set; }
        public string Massa { get; set; }
        public string Speed { get; set; }
        public string Condition { get; set; }
        public Nullable<int> Nachalnik { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Типы Типы { get; set; }
    }
}
