//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AturinKozlovNegmatov_Praktika2022_LokoTeh.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Типы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Типы()
        {
            this.Поезда = new HashSet<Поезда>();
        }
    
        public int Id_Type { get; set; }
        public string Тип { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поезда> Поезда { get; set; }
    }
}
