//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AturinKozlovNegmatov_Praktika2022_LokoTeh.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Учет_Запчастей
    {
        public int Id_Zapchasti { get; set; }
        public Nullable<int> Id_Nachalnika { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Date { get; set; }
        public int Id_Ucheta { get; set; }
    
        public virtual Запчасти Запчасти { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
